using System.ComponentModel.DataAnnotations;

namespace Todo_API.Models
{
  public class Todo
  {
    [Key]
    public int Id { get; set; }
    public int? ParentId { get; set; }
    [Required, StringLength(255)]
    public string Title { get; set; }
    [StringLength(500)]
    public string? Description { get; set; }
    [StringLength(100)]
    public string CreatedBy { get; set; }
    [StringLength(100)]
    public string? AssignedTo { get; set; }
    [Required, StringLength(20)]
    public string Status { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    }
}



/*
 * something like this in SQL:
 * 
 * CREATE TABLE Todos (
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ParentId INTEGER,
    Title VARCHAR(255),
    Description VARCHAR(500),
    CreatedBy VARCHAR(100),
    AssignedTo VARCHAR(100),
    Status VARCHAR(20), -- e.g. 'pending', 'in_progress', 'done'
    CreatedAt TIMESTAMP,
    UpdatedAt TIMESTAMP,
    FOREIGN KEY (ParentId) REFERENCES Todos(Id)
);
*/